use rand::seq::SliceRandom;
use std::collections::HashSet;
use std::fs::File;
use std::io::{BufRead, BufReader};

use crate::error::OptError;
use crate::search_state::{ProblemTrait, Rankable};

/// A sequence of city indices representing a Hamiltonian tour (0-indexed).
pub type TspTour = Vec<usize>;

/// A solution to the TSP problem.
///
/// - `tour` — ordered sequence of city indices forming the tour
/// - `objective` — total tour length
#[derive(Debug, Clone)]
pub struct TspSolution {
    /// Ordered sequence of city indices representing the tour.
    pub tour: TspTour,
    /// Total tour length.
    pub objective: f64,
}

impl Rankable for TspSolution {
    fn is_better_than(&self, other: &Self) -> bool {
        self.objective < other.objective
    }
}

impl ProblemTrait for TspWithCoordinates {
    type Solution = TspSolution;

    fn new_solution(&self, rng: &mut impl rand::Rng) -> TspSolution {
        let mut tour: TspTour = (0..self.get_n()).collect();
        tour.shuffle(rng);
        let objective = self
            .calculate_tour_length(&tour)
            .expect("tour generated by new_solution should always be valid");
        TspSolution { tour, objective }
    }
}

/// TSP problem instance storing city coordinates.
///
/// Distances are computed as Euclidean distances between 2D coordinate pairs.
#[derive(Debug, Clone)]
pub struct TspWithCoordinates {
    pub name: String,
    pub coordinates: Vec<(f64, f64)>,
}

impl TspWithCoordinates {
    pub fn new(name: String, coordinates: Vec<(f64, f64)>) -> Self {
        Self { name, coordinates }
    }

    /// Loads a TSP instance from a TSPLIB-format file.
    pub fn load_file(file_path: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let file = File::open(file_path)?;
        let reader = BufReader::new(file);
        let mut lines = reader.lines();
        let name = lines
            .next()
            .ok_or("File is empty")??
            .split_whitespace()
            .last()
            .ok_or("Not found name")?
            .to_string();

        // skip TYPE
        lines.next();
        // skip COMMENT
        lines.next();
        // skip DIMENSION
        let n = lines
            .next()
            .ok_or("Not found DIMENSION")??
            .split_whitespace()
            .last()
            .ok_or("Not found DIMENSION")?
            .parse::<usize>()?;
        // skip EDGE_WEIGHT_TYPE
        lines.next();
        // skip NODE_COORD_SECTION
        lines.next();

        let mut coord = vec![];
        for _ in 0..n {
            let line = lines.next().ok_or("Not found line")??;
            let mut iter = line.split_whitespace();

            // skip index
            let _ = iter.next();

            let x = iter.next().ok_or("Not found x")?.parse::<f64>()?;
            let y = iter.next().ok_or("Not found y")?.parse::<f64>()?;

            coord.push((x, y));
        }

        Ok(Self::new(name, coord))
    }

    /// Returns the number of cities.
    pub fn get_n(&self) -> usize {
        self.coordinates.len()
    }

    /// Returns the Euclidean distance between cities `i` and `j`.
    pub fn distance(&self, i: usize, j: usize) -> f64 {
        let (x1, y1) = self.coordinates[i];
        let (x2, y2) = self.coordinates[j];
        ((x1 - x2).powi(2) + (y1 - y2).powi(2)).sqrt()
    }

    /// Adds a new city with the given coordinates to the TSP instance.
    pub fn add_city(&mut self, xy: (f64, f64)) {
        self.coordinates.push(xy);
    }

    /// Calculates the total length of a tour.
    ///
    /// Returns an error if the tour length does not match the number of cities,
    /// or if any city appears more than once.
    pub fn calculate_tour_length(&self, tour: &TspTour) -> Result<f64, OptError> {
        if self.get_n() != tour.len() {
            return Err(OptError::InvalidState(format!(
                "The size of TSP ({}) and length of tour ({}) are not matched",
                self.get_n(),
                tour.len()
            )));
        }

        let mut arrived = HashSet::new();

        let mut length = 0.0;
        for ind in 0..self.get_n() {
            let i = tour[ind];

            if arrived.contains(&i) {
                return Err(OptError::InvalidState(format!(
                    "The city {} is already arrived",
                    i
                )));
            }

            let j = tour[(ind + 1) % self.get_n()];
            length += self.distance(i, j);

            arrived.insert(i);
        }

        Ok(length)
    }
}

#[cfg(test)]
mod tsp_coord_tests {
    use super::*;

    #[test]
    fn test_load_file() {
        let tsp_result = TspWithCoordinates::load_file("data/tsp/test_data.txt");
        assert!(tsp_result.is_ok());
        let tsp = tsp_result.unwrap();
        assert_eq!(tsp.name, "test");
        assert_eq!(tsp.coordinates.len(), 4);
    }

    #[test]
    fn test_distance() {
        let tsp_result = TspWithCoordinates::load_file("data/tsp/test_data.txt");
        assert!(tsp_result.is_ok());
        let tsp = tsp_result.unwrap();
        assert_eq!(tsp.distance(0, 1), 1.0);
        assert_eq!(tsp.distance(1, 2), 2.0);
    }

    #[test]
    fn test_not_match_size_tour() {
        let tsp_result = TspWithCoordinates::load_file("data/tsp/test_data.txt");
        assert!(tsp_result.is_ok());
        let tsp = tsp_result.unwrap();
        let invalid_tour = vec![0, 1];

        assert!(tsp.calculate_tour_length(&invalid_tour).is_err());
    }

    #[test]
    fn test_duplicated_tour() {
        let tsp_result = TspWithCoordinates::load_file("data/tsp/test_data.txt");
        assert!(tsp_result.is_ok());
        let tsp = tsp_result.unwrap();
        let invalid_tour = vec![0, 1, 0, 2];

        assert!(tsp.calculate_tour_length(&invalid_tour).is_err());
    }

    #[test]
    fn test_tour_length() {
        let tsp_result = TspWithCoordinates::load_file("data/tsp/test_data.txt");
        assert!(tsp_result.is_ok());
        let tsp = tsp_result.unwrap();
        let tour = vec![0, 1, 2, 3];
        assert_eq!(tsp.calculate_tour_length(&tour).unwrap(), 6.0);
    }
}
