use rand::seq::SliceRandom;
use std::collections::HashSet;
use std::sync::OnceLock;

use crate::error::OptError;
use crate::search_state::{Distance, ProblemTrait, Rankable};

/// A sequence of city indices representing a Hamiltonian tour (0-indexed).
pub type TspTour = Vec<usize>;
pub type TspEdge = (usize, usize);

/// A solution to the TSP problem.
///
/// - `tour` — ordered sequence of city indices forming the tour
/// - `objective` — total tour length
///
/// Move gains are computed on the fly from [`TspWithCoordinates::distance`]
/// (backed by the lazily built distance matrix), so no per-solution gain
/// cache is kept.
#[derive(Debug, Clone)]
pub struct TspSolution {
    /// Ordered sequence of city indices representing the tour.
    pub tour: TspTour,
    /// Total tour length.
    pub objective: f64,
}

impl Rankable for TspSolution {
    fn is_better_than(&self, other: &Self) -> bool {
        self.objective < other.objective
    }
}

impl Distance for TspSolution {
    /// Position-based dissimilarity: number of cities whose tour position differs.
    /// Not a metric in the strict sense, but a useful diversity proxy for GA
    /// parent selection.
    fn distance(&self, other: &Self) -> usize {
        self.tour
            .iter()
            .zip(other.tour.iter())
            .filter(|(a, b)| a != b)
            .count()
    }
}

impl ProblemTrait for TspWithCoordinates {
    type Solution = TspSolution;

    fn new_solution(&self, rng: &mut impl rand::Rng) -> TspSolution {
        let mut tour: TspTour = (0..self.get_n()).collect();
        tour.shuffle(rng);
        let objective = self
            .calculate_tour_length(&tour)
            .expect("tour generated by new_solution should always be valid");
        TspSolution { tour, objective }
    }
}

/// TSPLIB `EDGE_WEIGHT_TYPE` variants supported by [`TspWithCoordinates`].
///
/// Each variant selects the distance formula used by [`TspWithCoordinates::distance`].
/// `Continuous` is the default for programmatically constructed instances and
/// preserves the library's historical plain-Euclidean behavior; the remaining
/// variants match the integer-rounded formulas specified by TSPLIB so objective
/// values are comparable to published optima.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EdgeWeightType {
    /// Plain Euclidean distance (no rounding). Default for [`TspWithCoordinates::new`].
    Continuous,
    /// `nint(sqrt(dx^2 + dy^2))` — TSPLIB `EUC_2D`.
    Euc2d,
    /// `ceil(sqrt(dx^2 + dy^2))` — TSPLIB `CEIL_2D`.
    Ceil2d,
    /// TSPLIB pseudo-Euclidean distance (`ATT`): `r = sqrt((dx^2+dy^2)/10); t = nint(r); d = if t<r {t+1} else {t}`.
    Att,
    /// TSPLIB geographical distance (`GEO`). Coordinates are `DDD.MM` → radians;
    /// great-circle distance with Earth radius 6378.388 km, truncated.
    Geo,
}

/// TSP problem instance storing city coordinates.
///
/// Distances are computed via the formula selected by `edge_weight_type`.
/// For instances with at most [`DIST_MATRIX_MAX_N`] cities, the full distance
/// matrix is built lazily on first use, turning every subsequent
/// [`TspWithCoordinates::distance`] call into an O(1) lookup.
#[derive(Debug, Clone)]
pub struct TspWithCoordinates {
    pub name: String,
    pub coordinates: Vec<(f64, f64)>,
    pub edge_weight_type: EdgeWeightType,
    /// Lazily built `n × n` distance matrix (row-major). Only populated when
    /// `n <= DIST_MATRIX_MAX_N`; reset by [`TspWithCoordinates::add_city`].
    dist_matrix: OnceLock<Vec<f64>>,
}

/// Maximum number of cities for which the full distance matrix is precomputed
/// (memory: `n² × 8` bytes, i.e. 32 MB at the 2000-city cap). Larger instances
/// fall back to computing each distance on the fly.
pub const DIST_MATRIX_MAX_N: usize = 2000;

/// Converts a `DDD.MM` TSPLIB coordinate to radians (GEO distance helper).
#[inline]
fn geo_ddmm_to_rad(xy: f64) -> f64 {
    let deg = xy.trunc();
    let min = xy - deg;
    std::f64::consts::PI * (deg + 5.0 * min / 3.0) / 180.0
}

impl TspWithCoordinates {
    /// Creates a new instance with [`EdgeWeightType::Continuous`] distances.
    pub fn new(name: String, coordinates: Vec<(f64, f64)>) -> Self {
        Self {
            name,
            coordinates,
            edge_weight_type: EdgeWeightType::Continuous,
            dist_matrix: OnceLock::new(),
        }
    }

    /// Creates a new instance with an explicit TSPLIB edge-weight type.
    pub fn with_edge_weight_type(
        name: String,
        coordinates: Vec<(f64, f64)>,
        edge_weight_type: EdgeWeightType,
    ) -> Self {
        Self {
            name,
            coordinates,
            edge_weight_type,
            dist_matrix: OnceLock::new(),
        }
    }

    /// Loads a TSP instance from a TSPLIB-format file.
    pub fn load_file(path: impl AsRef<std::path::Path>) -> Result<Self, crate::error::OptError> {
        use crate::common::InstanceLines;

        let path = path.as_ref();
        let mut lines = InstanceLines::open(path)?;

        // Parse TSPLIB header lines until NODE_COORD_SECTION.
        // Accepts any key order, skips unknown keys (TYPE, COMMENT, DISPLAY_DATA_TYPE, ...),
        // and tolerates multi-line COMMENT fields.
        let mut name: Option<String> = None;
        let mut dimension: Option<usize> = None;
        let mut edge_weight_type: Option<String> = None;
        loop {
            let line = lines.next_line()?.ok_or_else(|| {
                lines.err("unexpected end of file, expected header line or 'NODE_COORD_SECTION'")
            })?;
            let trimmed = line.trim();
            if trimmed.is_empty() {
                continue;
            }
            // Section terminator — everything before it was header.
            let key_upper = trimmed
                .split(|c: char| c == ':' || c.is_whitespace())
                .next()
                .unwrap_or("")
                .to_ascii_uppercase();
            if key_upper == "NODE_COORD_SECTION" {
                break;
            }
            let value = trimmed
                .split_once(':')
                .map(|(_, v)| v.trim().to_string())
                .unwrap_or_default();
            match key_upper.as_str() {
                "NAME" => name = Some(value),
                "DIMENSION" => {
                    dimension =
                        Some(value.parse::<usize>().map_err(|e| {
                            lines.err(format!("failed to parse DIMENSION value: {e}"))
                        })?);
                }
                "EDGE_WEIGHT_TYPE" => edge_weight_type = Some(value),
                // TYPE / COMMENT / EDGE_WEIGHT_FORMAT / DISPLAY_DATA_TYPE / ... — skip
                _ => {}
            }
        }

        let n = dimension.ok_or_else(|| lines.err("'DIMENSION: N' not found in header"))?;
        let ewt_raw = edge_weight_type
            .ok_or_else(|| lines.err("'EDGE_WEIGHT_TYPE: ...' not found in header"))?;
        let ewt = match ewt_raw.to_ascii_uppercase().as_str() {
            "EUC_2D" => EdgeWeightType::Euc2d,
            "CEIL_2D" => EdgeWeightType::Ceil2d,
            "ATT" => EdgeWeightType::Att,
            "GEO" => EdgeWeightType::Geo,
            other => {
                return Err(lines.err(format!(
                    "unsupported EDGE_WEIGHT_TYPE '{other}' (supported: EUC_2D, CEIL_2D, ATT, GEO)"
                )));
            }
        };
        let name = name.unwrap_or_else(|| {
            path.file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("tsp")
                .to_string()
        });

        let mut coord = vec![];
        for city_idx in 0..n {
            let line = lines.next_line()?.ok_or_else(|| {
                lines.err(format!(
                    "unexpected end of file, expected coordinate for city {}/{}",
                    city_idx + 1,
                    n
                ))
            })?;
            let mut tokens = line.split_whitespace();

            // skip index
            let _ = tokens.next();

            let x: f64 = lines.parse_next(
                &mut tokens,
                &format!("x coordinate for city {}", city_idx + 1),
            )?;
            let y: f64 = lines.parse_next(
                &mut tokens,
                &format!("y coordinate for city {}", city_idx + 1),
            )?;

            coord.push((x, y));
        }

        Ok(Self::with_edge_weight_type(name, coord, ewt))
    }

    /// Returns the number of cities.
    pub fn get_n(&self) -> usize {
        self.coordinates.len()
    }

    /// Returns the directed edge `(i→j)` at position `k` in the tour.
    pub fn get_edge_from(&self, tour: &TspTour, k: usize) -> TspEdge {
        let n = tour.len();
        (tour[k], tour[(k + 1) % n])
    }

    /// Returns the distance between cities `i` and `j` using the formula selected
    /// by `self.edge_weight_type`.
    ///
    /// For instances with at most [`DIST_MATRIX_MAX_N`] cities, the full
    /// distance matrix is built lazily on the first call and subsequent calls
    /// are O(1) lookups; larger instances compute the formula on the fly.
    #[inline]
    pub fn distance(&self, i: usize, j: usize) -> f64 {
        let n = self.coordinates.len();
        if n <= DIST_MATRIX_MAX_N {
            let matrix = self.dist_matrix.get_or_init(|| {
                let mut m = Vec::with_capacity(n * n);
                for a in 0..n {
                    for b in 0..n {
                        m.push(self.compute_distance(a, b));
                    }
                }
                m
            });
            return matrix[i * n + j];
        }
        self.compute_distance(i, j)
    }

    /// Computes the distance formula directly from the coordinates.
    fn compute_distance(&self, i: usize, j: usize) -> f64 {
        let (x1, y1) = self.coordinates[i];
        let (x2, y2) = self.coordinates[j];
        match self.edge_weight_type {
            EdgeWeightType::Continuous => {
                let dx = x1 - x2;
                let dy = y1 - y2;
                (dx * dx + dy * dy).sqrt()
            }
            EdgeWeightType::Euc2d => {
                let dx = x1 - x2;
                let dy = y1 - y2;
                (dx * dx + dy * dy).sqrt().round()
            }
            EdgeWeightType::Ceil2d => {
                let dx = x1 - x2;
                let dy = y1 - y2;
                (dx * dx + dy * dy).sqrt().ceil()
            }
            EdgeWeightType::Att => {
                let dx = x1 - x2;
                let dy = y1 - y2;
                let r = ((dx * dx + dy * dy) / 10.0).sqrt();
                let t = r.round();
                if t < r { t + 1.0 } else { t }
            }
            EdgeWeightType::Geo => {
                // TSPLIB GEO: column 1 = latitude, column 2 = longitude, encoded DDD.MM.
                let lat_i = geo_ddmm_to_rad(x1);
                let long_i = geo_ddmm_to_rad(y1);
                let lat_j = geo_ddmm_to_rad(x2);
                let long_j = geo_ddmm_to_rad(y2);
                const RRR: f64 = 6378.388;
                let q1 = (long_i - long_j).cos();
                let q2 = (lat_i - lat_j).cos();
                let q3 = (lat_i + lat_j).cos();
                (RRR * (0.5 * ((1.0 + q1) * q2 - (1.0 - q1) * q3)).acos() + 1.0).trunc()
            }
        }
    }

    /// Adds a new city with the given coordinates to the TSP instance.
    pub fn add_city(&mut self, xy: (f64, f64)) {
        self.coordinates.push(xy);
        // The cached distance matrix (if any) is stale now.
        self.dist_matrix = OnceLock::new();
    }

    /// Returns the 2-opt gain for removing edges `a→b` and `c→d` and adding `a→c` and `b→d`
    /// (negative = improvement).
    pub fn calc_2opt_gain_cities(&self, e1: TspEdge, e2: TspEdge) -> f64 {
        let (a, b) = e1;
        let (c, d) = e2;
        self.distance(a, c) + self.distance(b, d) - self.distance(a, b) - self.distance(c, d)
    }

    /// Calculates the total length of a tour.
    ///
    /// Returns an error if the tour length does not match the number of cities,
    /// or if any city appears more than once.
    pub fn calculate_tour_length(&self, tour: &TspTour) -> Result<f64, OptError> {
        if self.get_n() != tour.len() {
            return Err(OptError::InvalidState(format!(
                "The size of TSP ({}) and length of tour ({}) are not matched",
                self.get_n(),
                tour.len()
            )));
        }

        let mut arrived = HashSet::new();

        let mut length = 0.0;
        for ind in 0..self.get_n() {
            let i = tour[ind];

            if arrived.contains(&i) {
                return Err(OptError::InvalidState(format!(
                    "The city {} is already arrived",
                    i
                )));
            }

            let e = self.get_edge_from(tour, ind);
            length += self.distance(e.0, e.1);

            arrived.insert(i);
        }

        Ok(length)
    }
}

#[cfg(test)]
mod tsp_coord_tests {
    use super::*;

    fn write_tmp(contents: &str) -> std::path::PathBuf {
        use std::io::Write;
        let mut path = std::env::temp_dir();
        let unique = format!(
            "optopus_tsp_{}_{}.tsp",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        );
        path.push(unique);
        let mut f = std::fs::File::create(&path).unwrap();
        f.write_all(contents.as_bytes()).unwrap();
        path
    }

    /// 4-city rectangular EUC_2D fixture: (0,0), (1,0), (1,2), (0,2).
    /// distance(0,1)=1, distance(1,2)=2; tour [0,1,2,3] length = 6.
    fn make_test_tsp_file() -> std::path::PathBuf {
        write_tmp(
            "NAME: test\n\
             TYPE: TSP\n\
             COMMENT: 4-city rectangle fixture\n\
             DIMENSION: 4\n\
             EDGE_WEIGHT_TYPE: EUC_2D\n\
             NODE_COORD_SECTION\n\
             1 0.0 0.0\n\
             2 1.0 0.0\n\
             3 1.0 2.0\n\
             4 0.0 2.0\n\
             EOF\n",
        )
    }

    #[test]
    fn test_load_file() {
        let path = make_test_tsp_file();
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.name, "test");
        assert_eq!(tsp.coordinates.len(), 4);
        assert_eq!(tsp.edge_weight_type, EdgeWeightType::Euc2d);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_distance() {
        let path = make_test_tsp_file();
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.distance(0, 1), 1.0);
        assert_eq!(tsp.distance(1, 2), 2.0);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_not_match_size_tour() {
        let path = make_test_tsp_file();
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert!(tsp.calculate_tour_length(&vec![0, 1]).is_err());
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_duplicated_tour() {
        let path = make_test_tsp_file();
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert!(tsp.calculate_tour_length(&vec![0, 1, 0, 2]).is_err());
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_tour_length() {
        let path = make_test_tsp_file();
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.calculate_tour_length(&vec![0, 1, 2, 3]).unwrap(), 6.0);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_file_multiline_comment() {
        let contents = "\
NAME: multi
TYPE: TSP
COMMENT: first line
COMMENT: second line
COMMENT: third line
DIMENSION: 3
EDGE_WEIGHT_TYPE: EUC_2D
NODE_COORD_SECTION
1 0.0 0.0
2 1.0 0.0
3 0.0 1.0
EOF
";
        let path = write_tmp(contents);
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.name, "multi");
        assert_eq!(tsp.coordinates.len(), 3);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_file_unsupported_edge_weight_type() {
        let contents = "\
NAME: explicit
TYPE: TSP
COMMENT: explicit distance matrix
DIMENSION: 2
EDGE_WEIGHT_TYPE: EXPLICIT
NODE_COORD_SECTION
1 0.0 0.0
2 1.0 1.0
EOF
";
        let path = write_tmp(contents);
        let result = TspWithCoordinates::load_file(path.to_str().unwrap());
        assert!(result.is_err(), "EXPLICIT should be rejected");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_file_att() {
        let path = write_tmp(
            "NAME: att_fixture\n\
             TYPE: TSP\n\
             DIMENSION: 3\n\
             EDGE_WEIGHT_TYPE: ATT\n\
             NODE_COORD_SECTION\n\
             1 0.0 0.0\n\
             2 10.0 0.0\n\
             3 5.0 5.0\n\
             EOF\n",
        );
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.coordinates.len(), 3);
        assert_eq!(tsp.edge_weight_type, EdgeWeightType::Att);
        // r = sqrt(100 / 10) ≈ 3.162; t = 3; 3 < 3.162 → d = 4
        assert_eq!(tsp.distance(0, 1), 4.0);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_file_geo() {
        // Coordinates in TSPLIB DDD.MM format (degrees.minutes).
        let path = write_tmp(
            "NAME: geo_fixture\n\
             TYPE: TSP\n\
             DIMENSION: 2\n\
             EDGE_WEIGHT_TYPE: GEO\n\
             NODE_COORD_SECTION\n\
             1 16.47 96.10\n\
             2 14.05 98.12\n\
             EOF\n",
        );
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.coordinates.len(), 2);
        assert_eq!(tsp.edge_weight_type, EdgeWeightType::Geo);
        let d = tsp.distance(0, 1);
        assert!(d > 0.0);
        assert_eq!(d, d.trunc(), "GEO distances must be integer-valued");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_file_ceil_2d() {
        let path = write_tmp(
            "NAME: ceil_fixture\n\
             TYPE: TSP\n\
             DIMENSION: 2\n\
             EDGE_WEIGHT_TYPE: CEIL_2D\n\
             NODE_COORD_SECTION\n\
             1 0.0 0.0\n\
             2 1.0 1.0\n\
             EOF\n",
        );
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.edge_weight_type, EdgeWeightType::Ceil2d);
        // ceil(sqrt(2)) = 2, whereas EUC_2D would round to 1.
        assert_eq!(tsp.distance(0, 1), 2.0);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_distance_att_formula() {
        // ATT formula: r = sqrt((dx^2 + dy^2) / 10); t = nint(r); d = if t<r {t+1} else {t}
        let tsp = TspWithCoordinates::with_edge_weight_type(
            "att".into(),
            vec![(0.0, 0.0), (10.0, 0.0)],
            EdgeWeightType::Att,
        );
        // r = sqrt(100 / 10) = sqrt(10) ≈ 3.162; t = 3; 3 < 3.162 → d = 4
        assert_eq!(tsp.distance(0, 1), 4.0);
    }

    #[test]
    fn test_distance_geo_formula() {
        // Two cities at (0.0, 0.0) and (0.0, 0.0) → identical location → distance ≈ 1 (acos(1)=0, +1 truncated).
        let tsp = TspWithCoordinates::with_edge_weight_type(
            "geo".into(),
            vec![(0.0, 0.0), (0.0, 0.0)],
            EdgeWeightType::Geo,
        );
        assert_eq!(tsp.distance(0, 1), 1.0);

        // Sanity: positive coordinates give a positive geodesic distance.
        let tsp2 = TspWithCoordinates::with_edge_weight_type(
            "geo2".into(),
            vec![(0.0, 0.0), (10.0, 10.0)],
            EdgeWeightType::Geo,
        );
        assert!(tsp2.distance(0, 1) > 1.0);
    }

    #[test]
    fn test_load_file_missing_dimension() {
        let contents = "\
NAME: nodim
TYPE: TSP
COMMENT: missing dimension
EDGE_WEIGHT_TYPE: EUC_2D
NODE_COORD_SECTION
1 0.0 0.0
";
        let path = write_tmp(contents);
        let result = TspWithCoordinates::load_file(path.to_str().unwrap());
        assert!(result.is_err(), "missing DIMENSION should error");
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_load_file_permuted_header_order() {
        let contents = "\
EDGE_WEIGHT_TYPE: EUC_2D
COMMENT: arbitrary order
DIMENSION: 2
TYPE: TSP
NAME: permuted
NODE_COORD_SECTION
1 0.0 0.0
2 3.0 4.0
EOF
";
        let path = write_tmp(contents);
        let tsp = TspWithCoordinates::load_file(path.to_str().unwrap()).unwrap();
        assert_eq!(tsp.name, "permuted");
        assert_eq!(tsp.coordinates.len(), 2);
        assert!((tsp.distance(0, 1) - 5.0).abs() < 1e-9);
        let _ = std::fs::remove_file(&path);
    }
}
